[[headers]]
  for = "/*"
  [headers.values]
    Link = '''
    </style.css>; rel=preload; as=style,
    <https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap>; rel=preload; as=style
    '''
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
