# 1. Agresywny cache dla małego pliku CSS i obrazków WebP
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 2. Bezpieczeństwo dla głównej strony (zawsze świeża wersja)
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 3. Dodatkowe optymalizacje serwera
[build.processing]
  skip_node_bundler = true
[build.processing.css]
  minify = true # Nawet przy 5.8KB warto usunąć zbędne spacje
[build.processing.images]
  compress = true
