[[headers]]
  for = "/*"
  [headers.values]
    # Przyspieszamy FCP poprzez natychmiastowe pobieranie stylu i fontów
    Link = '''
    </style.css>; rel=preload; as=style,
    <https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap>; rel=preload; as=style
    '''

    # Optymalizacja cache dla przeglądarki
    Cache-Control = "public, max-age=31536000, immutable"

    # Podstawowe zabezpieczenie
    X-Content-Type-Options = "nosniff"
